/**
 * @brief Parallax application MQTT Explorer
 * Application taht connects to the MQTT broker and watches all files with selected topics
 * @author xjurke02
 * @author xvanop01
 * @note Generated by Qt
 */
#include "widget.h"
#include <QApplication>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    Widget w;
    w.show();

    return a.exec();
}
